// Generated by CoffeeScript 1.9.3
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use(express["static"]('public'));

  app.listen(3000, function() {
    return console.log('Client listening to 3000...');
  });

  app.get('/', function(req, res) {
    return res.sendFile('./public/index.html');
  });

}).call(this);
