// Generated by CoffeeScript 1.9.3
(function() {
  var axon, socket;

  axon = require('axon');

  socket = axon.socket('sub');

  socket.connect(8000);

  socket.on('error', function(err) {
    throw err;
  });

  module.exports = socket;

}).call(this);
