// Generated by CoffeeScript 1.9.3
(function() {
  var request;

  request = require('request');

  exports.get = function(callback) {
    return request('http://localhost:8000/badges', function(err, res, body) {
      return callback(err, JSON.parse(body));
    });
  };

}).call(this);
